//eslint-disable-next-line
export  const SET_MY_TEAM_TIMESHEET_LIST = "SET_MY_TEAM_TIMESHEET_LIST";
export  const OPEN_ACTION_TIMESHEET_MODAL = "OPEN_ACTION_TIMESHEET_MODAL";
export  const CLOSE_ACTION_TIMESHEET_MODAL = "CLOSE_ACTION_TIMESHEET_MODAL";
export  const CLEAR_TIMESHEET_ACTION_ERROR = "CLEAR_TIMESHEET_ACTION_ERROR";
export  const CREATE_TIMESHEET_PENDING = "CREATE_TIMESHEET_PENDING";
export  const CLEAR_TIMESHEET_ERROR = "CLEAR_TIMESHEET_ERROR";
export  const CREATE_MY_TEAM_TIMESHEET_SUCCESS = "CREATE_MY_TEAM_TIMESHEET_SUCCESS";
export  const UPDATE_MY_TEAM_TIMESHEET_ERROR = "UPDATE_MY_TEAM_TIMESHEET_ERROR";